### PR TITLE
Python 3 and OS X compatibility

### PR DESCRIPTION
**Pull request by alexchandel**
Three changes happened:
- I ran 2to3 for some trivial syntax/import changes
- I changed the package name to the lowercase `appkit`, for PEP 8 compliance and name-collisions
- I gitignored some build files

### CODE REVIEW

**Comment by nitipit** [comment]
Thanks, I'll review the commits :)

**Comment by nitipit** [comment]
@alexchandel  , Do you have GTK3 installed in Mac OSX ? :P

**Comment by alexchandel** [comment]
@nitipit No just GTK 2.24. I'd have to build all the Python packages by hand against GTK+3.

Why, is Python GTK+3 required? Or bugs?

**Comment by nitipit** [comment]
@alexchandel Nope, just wonder, I've never tested it under Mac OSX :)
only on my fedora with GTK3 installed.

**Comment by nitipit** [comment]
The code break the test running with python2.7 .. trying to figure out how to manage it .

**Comment by nitipit** [comment]
Merge in progress, need to fix some thing :)
https://github.com/nitipit/appkit/tree/16-alexchandel-merge

**Pull request merged**
